version: '3'
services:
  mysqldoc:
    container_name: mysqldoc
    image: mysql
    ports:
      - "32779:3306"
    environment:
      MYSQL_USER: springuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: document
    networks:
      - production
    volumes:
      - /data/database:/var/lib/mysql
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      timeout: 20s
      retries: 10
    restart: always
  devschool_api:
    container_name: devschool_api
    image: grupodevschool2021/devschool_api
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldoc:3306/document
    ports:
      - "8080:8080"
    networks:
      - production
    depends_on:
      - mysqldoc
    restart: always
  pepino-surpresa-front:
    image: grupodevschool2021/pepino-surpresa
    depends_on:
      - "devschool_api"
    ports:
      - "4200:80"
    networks:
      - production
networks:
  production:
    driver: bridge

