version: '3'
services:
  mysqldoc:
    container_name: mysqldoc
    build:
      context: .
      dockerfile: ./mysql.dockerfile
    image: mysql
    ports:
      - "32779:3306"
    environment:
      MYSQL_USER: springuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: document
    networks:
      - production
    volumes:
      - /data/database:/var/lib/mysql
  devschool_api:
    container_name: devschool_api
    build:
      context: .
      dockerfile: ./Dockerfile
    image: devschool_api
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldoc:3306/document
    ports:
      - "8080:8080"
    networks:
      - production
    depends_on:
      - mysqldoc
networks:
  production:
    driver: bridge
